use zkbd and configure it for mac

diff --git a/.config/zsh/zsh_keys b/.config/zsh/zsh_keys
--- a/.config/zsh/zsh_keys
+++ b/.config/zsh/zsh_keys
@@ -1,71 +1,34 @@
-case $TERM in
-	 *linux)
-	    bindkey "^[[2~" yank
-	    bindkey "^[[3~" delete-char
-	    bindkey "^[[5~" up-line-or-history
-	    bindkey "^[[6~" down-line-or-history
-	    bindkey "^[[1~" beginning-of-line
-	    bindkey "^[[4~" end-of-line
-	    bindkey "^[e" expand-cmd-path ## C-e for expanding path of typed command
-	    bindkey "^[[A" up-line-or-search ## up arrow for back-history-search
-	    bindkey "^[[B" down-line-or-search ## down arrow for fwd-history-search
-	    bindkey " " magic-space ## do history expansion on space
-	 ;;
-	 *xterm*|rxvt*|(dt|k|E)term)
-	    bindkey "^[[2~" yank
-	    bindkey "^[[3~" delete-char
-	    bindkey "^[[5~" up-line-or-history
-	    bindkey "^[[6~" down-line-or-history
-	    bindkey "^[[7~" beginning-of-line
-	    bindkey "^[[8~" end-of-line
-	    bindkey "^E" end-of-line
-	    bindkey "^A" beginning-of-line
-	    bindkey "^[d" kill-word
-	    bindkey "^[[A" up-line-or-search ## up arrow for back-history-search
-	    bindkey "^[[B" down-line-or-search ## down arrow for fwd-history-search
-	    bindkey " " magic-space ## do history expansion on space
-        bindkey "^R" history-incremental-search-backward
-	 ;;
-	 screen*)
-	    bindkey "^[[2~" yank
-	    bindkey "^[[3~" delete-char
-	    bindkey "^[[5~" up-line-or-history
-	    bindkey "^[[6~" down-line-or-history
-	    bindkey "^[[1~" beginning-of-line
-	    bindkey "^[[4~" end-of-line
-	    bindkey "^A" beginning-of-line
-	    bindkey "^E" end-of-line
-        bindkey "^[f" forward-word
-        bindkey "^[b" backward-word
-	    bindkey "^[d" kill-word
-	    bindkey "^[t" transpose-word
-	    bindkey "^[[A" history-search-backward ## up arrow for back-history-search
-	    bindkey "^[[B" history-search-forward ## down arrow for fwd-history-search
-	    bindkey " " magic-space ## do history expansion on space
-        bindkey "^R" history-incremental-search-backward
-	 ;;
- esac
+autoload zkbd
 
- # Перебор истории команд как в Vim (с совпадением строки левее курсора).
- # # Любезно предоставлено Sir Raorn.
- # bindkey    "^[[A" history-beginning-search-backward
- # bindkey -a "^[[A" history-beginning-search-backward
- # bindkey    "^[[B" history-beginning-search-forward
- # bindkey -a "^[[B" history-beginning-search-forward
- #
- # # дополнение по истории, ^X^Z включить ^Z выключить
- # autoload -U predict-on
- # zle -N predict-on
- # zle -N predict-off
- # bindkey -M emacs "^X^Z" predict-on
- # bindkey -M emacs "^Z" predict-off
- # # peжuм нaвuгaцuu в cтuлe emacs
- # bindkey -e
- # # режим редактирования команды, вызывает для этого то что в $EDITOR
- # autoload -U edit-command-line
- # # Вызов редактора для редактирования строки ввода (хоткей в стиле emacs)
- # # bindkey -M vicmd v edit-command-line для командного режима vi
- # zle -N edit-command-line
- # bindkey -M emacs "^X^E" edit-command-line
- # #завершить слово команду
- # bindkey -M emacs "^N" complete-word
+ZKBD_DIR=$HOME/.config/zsh/zkbd
+
+function zkbd_file() {
+    [[ -f $ZKBD_DIR/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' "$ZKBD_DIR/${TERM}-${VENDOR}-${OSTYPE}" && return 0
+    [[ -f $ZKBD_DIR/${TERM}-${DISPLAY}          ]] && printf '%s' "$ZKBD_DIR/${TERM}-${DISPLAY}"          && return 0
+    return 1
+}
+
+[[ ! -d $ZKBD_DIR ]] && mkdir $ZKBD_DIR
+keyfile=$(zkbd_file)
+ret=$?
+if [[ ${ret} -ne 0 ]]; then
+    zkbd
+    keyfile=$(zkbd_file)
+    ret=$?
+fi
+if [[ ${ret} -eq 0 ]] ; then
+    source "${keyfile}"
+else
+    printf 'Failed to setup keys using zkbd.\n'
+fi
+unfunction zkbd_file; unset keyfile ret
+
+# setup key accordingly
+[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
+[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
+[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
+[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
+[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
+[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
+[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
+[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
